<?php include('components/Header.php'); ?>
<?php include('components/BannerPromotion.php'); ?>
<?php include('components/CategoryIndex.php'); ?>
<?php include('components/banner_index.php'); ?>
<?php include('components/map.php'); ?>
<?php include('components/popularBrands.php'); ?>
<?php include('components/quote.php'); ?>
<?php include('components/blog.php'); ?>
<?php include('components/serving_wine.php'); ?>
<?php include('components/buy_index.php'); ?>
<?php include('components/Footer.php'); ?>